name: xayn_readability
description: A starting point for Dart libraries or applications.
version: 0.0.1
publish_to: none
homepage: https://www.xayn.com

environment:
  sdk: '>=2.14.0 <3.0.0'
  flutter: '>=2.0.0'

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.16.0
  flutter_widget_from_html_core: ^0.9.1
  html: ^0.15.0
  http_client: ^1.5.1
  xayn_readability_core:
    git:
      url: git@github.com:xaynetwork/xayn_readability_core.git
      ref: 7a7f329df28f95e4dd150c723aeaa635737b4f38

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^2.0.1
